name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # каждый день
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: missirina1
          outputs: |
            ./github-contribution-grid-snake.svg

      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate snake animation"
          add: "github-contribution-grid-snake.svg"
